You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.


class Solution {
    public char findTheDifference(String s, String t) {
        int [] count = new int [26];
        for (char ch : s.toCharArray()) {
            count[ch - 'a'] += 1;
        }
        for (char ch : t.toCharArray()) {
            count[ch - 'a'] -= 1;
        }
        char result = '-';
        for (int i=0; i<26; i++) {
            int number = count[i];
            if (number == -1) {
                result = (char)('a' + i);
            }
        }
        return result;
    }
}